package app.bola.taskforge.event;

public enum EventType {
	
	TASK_CREATED,
	TASK_UPDATED,
	TASK_DELETED,
	TASK_ASSIGNED,
	TASK_COMPLETED,
	TASK_COMMENTED,
	USER_REGISTERED,
	USER_LOGGED_IN,
	USER_LOGGED_OUT,
	ORGANIZATION_CREATED,
	ORGANIZATION_UPDATED,
	ORGANIZATION_DELETED,
	NOTIFICATION_SENT,
	ERROR_OCCURRED
}
