package app.bola.taskforge.domain.enums;

public enum NotificationType {
	
	TASK_DUE,
	TASK_CREATED,
	TASK_ASSIGNED,
	TASK_COMPLETED,
	TASK_UPDATED,
	TASK_DELETED,
	PROJECT_CREATED,
	PROJECT_UPDATED,
	PROJECT_DELETED,
	PROJECT_COMPLETED,
	MEMBER_ADDED,
	MEMBER_INVITED,
	MEMBER_REMOVED,
	COMMENT_ADDED,
	COMMENT_REPLIED,
	MENTIONED_IN_COMMENT,
}
                          	