package app.bola.taskforge.domain.enums;

public enum NotificationType {
	
	EMAIL,
	IN_APP,
	TEXT_MESSAGE
	
	
//	TASK_CREATED,
//	TASK_ASSIGNED,
//	TASK_COMPLETED,
//	TASK_UPDATED,
//	TASK_DELETED,
//	PROJECT_CREATED,
//	PROJECT_UPDATED,
//	PROJECT_DELETED,
//	PROJECT_COMPLETED,
//	MEMBER_ADDED,
//	MEMBER_REMOVED,
//	COMMENT_ADDED,
//	COMMENT_REPLIED,
}
